"""
app/food_intelligence.py
────────────────────────────────────────────────────────────────────────────
Thin compatibility shim — all real logic moved to knowledge_engine.py.
Kept so existing imports don't break.
"""
from app.knowledge_engine import estimate_nutrition, build_week_summary


def analyse_foods(meals, herbal_drinks, raw_message=""):
    """Compatibility wrapper — returns minimal dict for existing callers."""
    nutrition = estimate_nutrition(meals or [], herbal_drinks or [], raw_message)
    return {
        "insights":      [],   # now generated by knowledge_engine.get_food_and_cycle_insight
        "nutrition":     nutrition,
        "ayurvedic_foods": {},
        "gluten_foods":  [],
        "dairy_foods":   [],
        "caffeine_foods": [
            f for f in (meals or []) + (herbal_drinks or [])
            if any(c in str(f).lower() for c in ["chai","coffee","tea","caffeine"])
        ],
    }


def correlate_food_and_pain(logs):
    """Compatibility wrapper — correlations now handled in build_week_summary."""
    return {"correlations": [], "top_protective": [], "top_harmful": []}


def food_summary_for_report(logs):
    """Compatibility wrapper."""
    return build_week_summary(logs)
